import 'package:grocery_app/models/product.dart';

List<Product> productsDummyData = [
  Product(
    name: "Apples",
    description: "Fresh and juicy apples",
    price: 2.99,
    category: "Fruits",
    image: 'https://cdn.pixabay.com/photo/2018/04/02/11/51/apple-3283668_1280.png',
  ),
  Product(
    name: "Bananas",
    description: "Ripe and delicious bananas",
    price: 1.99,
    category: "Fruits",
    image: 'https://cdn.pixabay.com/photo/2021/02/10/13/04/banana-6002011_640.jpg',
  ),
  Product(
    name: "Milk",
    description: "Whole milk, 1 gallon",
    price: 3.49,
    category: "Dairy",
    image: 'https://cdn.pixabay.com/photo/2022/05/29/03/25/milk-7228322_640.jpg',
  ),
  Product(
    name: "Bread",
    description: "Whole wheat bread",
    price: 2.99,
    category: "Bakery",
    image: 'https://cdn.pixabay.com/photo/2018/02/26/02/43/bread-3182199_640.png',
  ),
  Product(
    name: "Eggs",
    description: "Large eggs, 12 count",
    price: 2.29,
    category: "Dairy",
    image: 'https://img.freepik.com/free-photo/three-fresh-organic-raw-eggs-isolated-white-surface_114579-43677.jpg?size=626&ext=jpg',
  ),
  Product(
    image: 'https://as1.ftcdn.net/v2/jpg/02/08/75/56/1000_F_208755651_TQ5DW7M9U5Dd95TtbMdu1hOWQM0ai4f1.jpg',
    name: "Chicken Breast",
    description: "Boneless, skinless chicken breast",
    price: 5.99,
    category: "Meat",
  ),
  Product(
    name: "Rice",
    description: "Long grain white rice, 5 lb",
    price: 4.99,
    category: "Grains",
    image: 'https://m.media-amazon.com/images/I/51yFtsNy+qL._SY300_SX300_.jpg',
  ),
  Product(
    name: "Pasta",
    description: "Spaghetti pasta, 16 oz",
    price: 1.49,
    category: "Pasta",
    image: 'https://m.media-amazon.com/images/I/51VfvocMgDL._SX300_SY300_QL70_FMwebp_.jpg',
  ),
  Product(
    name: "Tomatoes",
    description: "Vine-ripened tomatoes",
    price: 2.49,
    category: "Vegetables",
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/330px-Tomato_je.jpg',
  ),
  Product(
    name: "Spinach",
    description: "Fresh spinach leaves, 8 oz",
    price: 1.99,
    category: "Vegetables",
    image: 'https://www.wikijuices.com/wp-content/uploads/2020/12/spinach-bunch.jpg',
  ),
  Product(
    name: "Carrots",
    description: "Fresh carrots, 1 lb",
    price: 0.99,
    category: "Vegetables",
    image: 'https://freepngimg.com/thumb/grocery/41619-7-groceries-free-download-image.png',
  ),
  Product(
    name: "Carrots",
    description: "Fresh carrots, rich in beta-carotene and perfect for salads or roasting, 1 lb",
    price: 0.99,
    category: "Vegetables",
    image: "https://example.com/carrots.jpg",
  ),
  Product(
    name: "Potatoes",
    description: "Russet potatoes, great for mashing, baking, or frying, 5 lb",
    price: 3.99,
    category: "Vegetables",
    image: "https://example.com/potatoes.jpg",
  ),
  Product(
    name: "Onions",
    description: "Yellow onions, versatile ingredient for soups, stews, and stir-fries, 3 lb",
    price: 2.49,
    category: "Vegetables",
    image: "https://example.com/onions.jpg",
  ),
  Product(
    name: "Oranges",
    description: "Sweet and tangy oranges, packed with vitamin C and perfect for fresh juice, 5 lb",
    price: 4.99,
    category: "Fruits",
    image: "https://example.com/oranges.jpg",
  ),
  Product(
    name: "Lettuce",
    description: "Crisp and fresh lettuce, ideal for salads, sandwiches, and wraps, 1 head",
    price: 1.49,
    category: "Vegetables",
    image: "https://example.com/lettuce.jpg",
  ),
  Product(
    name: "Cereal",
    description: "Whole grain cereal with a mix of grains and flakes, a nutritious breakfast option, 16 oz",
    price: 3.99,
    category: "Breakfast",
    image: "https://example.com/cereal.jpg",
  ),
  Product(
    name: "Coffee",
    description: "Medium roast ground coffee, rich and bold flavor to kickstart your day, 12 oz",
    price: 5.99,
    category: "Beverages",
    image: "https://example.com/coffee.jpg",
  ),
  Product(
    name: "Tea",
    description: "Green tea bags, antioxidant-rich and soothing, perfect for a calming moment, 20 count",
    price: 2.49,
    category: "Beverages",
    image: "https://example.com/tea.jpg",
  ),
  Product(
    name: "Butter",
    description: "Salted butter, creamy and delicious, adds flavor to your cooking and baking, 1 lb",
    price: 2.99,
    category: "Dairy",
    image: "https://example.com/butter.jpg",
  ),
  Product(
    name: "Yogurt",
    description: "Greek yogurt, creamy and tangy, packed with protein and probiotics, 32 oz",
    price: 3.49,
    category: "Dairy",
    image: "https://example.com/yogurt.jpg",
  ),
];
